blank_issues_enabled: false
contact_links:
    - name: View common issues
      url: https://github.com/OMGitzFROST/MessageCraft/issues/1
      about: Check the list of known common issues to see if it solves your problem.
    - name: Check past help requests
      url: https://github.com/OMGitzFROST/MessageCraft/discussions/categories/q-a
      about: Visit the Q&A forum to search for previous help requests.
    - name: Check past feature suggestions
      url: https://github.com/OMGitzFROST/MessageCraft/discussions/categories/ideas-and-features
      about: Visit the Feature Suggestions forum to view and discuss existing feature suggestions.
    - name: Create help request
      url: https://github.com/OMGitzFROST/MessageCraft/discussions/new?category=q-a
      about: Create a support ticket to get help from developers.
    - name: Suggest a feature
      url: https://github.com/OMGitzFROST/MessageCraft/discussions/new?category=ideas-and-features
      about: Suggest new features for MessageCraft